production: 
  encoding: unicode
  adapter: postgresql
  username: username
  port: 5432
  host: hostname
  database: database
  password: password

development:
  adapter: sqlite3
  database: config/btsgroup.db
